### ISSUE TITLE
Salvare la configurazione

### ISSUE THREAD

**Issue by GiovanniCardamone** [vbextreme/EasyFramework#1]
Sarebbe un'ottima cosa salvare la configurazione fra una partita e l'altra.

Attualmente quando si riapre il gioco viene caricata sempre la configurazione di default.

**Comment by vbextreme** [comment]
Penso tu ti riferisca al gioco MagixCubic, questa è la sezione easyframework che poco centra col gioco in se stesso e le sue opzioni.

**Comment by koalization** [comment]
Si scrive "c'entra", non "centra".. ignorante.
